site_name: Amber Documentation

nav: 
#    - Home:
#      - Intel Amber: index.md
    - Amber Integrations: 
      - Amber Integrations: Integrations/integrations-overview.md
      - Gramine Integration: Integrations/gramene-integration.md
      - Amber Client Integration: Integrations/client-integration.md
    - API Documentation:
      - Overview: rest/overview.md
      - Policies:
        - Overview: rest/Policies/Policies Management Service overview.md
        - Create New Policy: rest/Policies/api1-policies.post.md
        - Search Policy: rest/Policies/api1-policies.get.md
        - Delete Policy: rest/Policies/api1-policies.delete.md
      - Ingress:
        - Create New Policy: rest/Ingress/api1-ingress.post.md
        - Search Policy: rest/Ingress/api1-ingress.get.md
        - Delete Policy: rest/Ingress/api1-ingress.delete.md
        - Update Policy: rest/Ingress/api1-ingress.put.md
      - Version:
        - Get Application Version: rest/Version/api1-version.get.md
      - ServiceOffers:
        - Search ServiceOffers: rest/ServiceOffers/api1-serviceoffers.get.md
      - Products:
        - Search Products: rest/Products/api1-products-get.md
      - Tenants:
        - Retrieve Tenant: rest\Tenants\api1-tenants.get.md
        - Add Tenant User: rest\Tenants\api1-tenants.post.md
        - Update User Roles: rest\Tenants\api1-tenants.put.md
        - Delete User: rest\Tenants\api1-tenants.delete.md
      - Services:
        - Delete Services: rest\Services\api1-services.delete.md
        - Retrieve Services: rest\Services\api1-services.get.md
        - Add Services: rest\Services\api1-services.post.md
      - Subscriptions:
        - Delete Subscriptions: rest\Subscriptions\api1-subscriptions.delete.md
        - Retrieve Subscriptions: rest\Subscriptions\api1-subscriptions.get.md
        - Add Subscriptions: rest\Subscriptions\api1-subscriptions.post.md
        - Update Subscriptions: rest\Subscriptions\api1-subscriptions.put.md
      - Users:
        - Delete Users: rest\Users\api1-users-delete.md
        - Retrieve Users: rest\Users\api1-users.get.md
        - Upodate Users: rest\Users\api1-users-post.md
      - Faithful Verification Report:
        - Create Report: rest\Reports\faithfulVerificationReport.md
    - Workflows:
      - Workflows: workflow\Worlkflow\Workflow-Overview.md
      - About Intel Amber: workflow/About-Amber/About-Amber.md
      - Subscribing to Amber: 
        - Subscription levels: workflow/Subscription-Levels/Subsription-Levels.md
        - Premium: workflow/Subscription-Levels/Premium-Level.md
        - Basic: workflow/Subscription-Levels/Basic-Level.md
        - Changing your Subscription: workflow/Subscription-Levels/Change-Subscription.md        
      - Managing Users: workflow/tutorials/managing-users.md
      - Creating API keys: workflow/tutorials/creating-api-keys.md
      - Policy Management: workflow/tutorials/policy-management.md
      - Reports and Metrics: workflow/tutorials/reports-metrics.md
    - Use Case Examples:
      - Overview: workflow/Use-Cases/overview.md
      - Zero Trust Network Access: workflow/Use-Cases/Zero Trust Network Access.md
      - Block Chain: workflow/Use-Cases/Block Chain.md
      - Confidential Container Using Gramine: workflow/Use-Cases/Confidential Container User Gramine.md
      - Federal Learning: workflow/Use-Cases/Federal Learning.md
      - Privacy Preserving Confidential Computing: workflow/Use-Cases/Privacy Preserving Confidential Computing.md
      - Privacy Preserving Machine Learning: workflow/Use-Cases/Privacy Preserving Machine Learning.md
      - Secret Key Management: workflow/Use-Cases/Secret Key Management.md
      - Trusted Multi-Party Compute: workflow/Use-Cases/Trusted Multi-Party Compute.md
      
    - CLI:
      - CLI Examples: workflow/cli/cli-examples.md
    - Value Added Services:
      - Key Broker Service: Downloads\KBS\kbs.md
      - TEE Caching Service: Downloads\TCS\tcs.md
      - Faithful Verifier: Downloads\FVV\FaithfulVerifier.md

theme:
   name: material
   font: 
     code: Fira Code
     text: Helvetica               
   palette:
    - scheme: default
      primary: light blue
      accent: amber
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
   logo: images/InteLogo.png
   favicon: images/InteLogo.png
   icon:
    repo: fontawesome/brands/github
   features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - search.suggest
    - navigation.tracking
    - navigation.section
    - navigation.expand
    - toc.follow
markdown_extensions:
  - toc:
        permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - markdown.extensions.tables
  - pymdownx.tabbed: 
        alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  

theme:
   name: material
   logo: assets/InteLogo.png
   font: 
     code: Fira Code
     text: Helvetica               
   palette:
    - scheme: default
      primary: Light Blue 
      accent: amber
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        

extra_css:
  - stylesheets/extra.css